#
# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.
#
# Add icons of general interest
#
/control/execute icons.mac
#
# File menu :
/gui/addMenu file File
/gui/addButton file Quit exit
#
# Gun menu :
/gui/addMenu gun Gun
/gui/addButton gun "0.025 eV"  "/gun/energy 0.025 eV"
/gui/addButton gun "0.1 eV"  "/gun/energy 0.1 eV"
/gui/addButton gun "1 eV"  "/gun/energy 1 eV"
#
# LD menu :
/gui/addMenu ld LD
/gui/addButton ld "1" "/model/setLD 1"
/gui/addButton ld "25" "/model/setLD 25"
/gui/addButton ld "50" "/model/setLD 50"
/gui/addButton ld "75" "/model/setLD 75"
/gui/addButton ld "100" "/model/setLD 100"
/gui/addButton ld "200" "/model/setLD 200"
#
# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wireframe"
/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
#
# To limit the output flow in the "dump" widget :
/run/printProgress 100
#
# User defined icon :
/gui/addIcon "Run beam on" user_icon "/run/beamOn 25" run.png 
